# Generated by Django 5.1 on 2025-09-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_owner_alter_pledge_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='poemline',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='storyverse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
