# Generated by Django 5.2.7 on 2025-10-28 04:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pledge_poemline_pledge_storyverse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='poemline',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='storyverse',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(help_text='Number of verses/paragraphs contributed', validators=[django.core.validators.MinValueValidator(1, message='Must contribute at least 1 verse/paragraph'), django.core.validators.MaxValueValidator(10, message='Cannot exceed 10 verses/paragraphs per contribution')]),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_pledges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='genre',
            field=models.CharField(choices=[('poetry', 'Poetry'), ('story', 'Story')], default='story', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(help_text='Maximum number of contributions allowed', validators=[django.core.validators.MinValueValidator(1, message='Must allow at least 1 contribution'), django.core.validators.MaxValueValidator(100, message='Cannot exceed 100 contributions')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Project cover image (optional, max 2MB)', null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='poemstart',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='storystart',
            field=models.TextField(blank=True),
        ),
    ]
