# Generated by Django 5.2.7 on 2025-10-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_pledge_anonymous_remove_pledge_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project cover image (optional, max 2MB)', null=True, upload_to='project_images/'),
        ),
    ]
