# Generated by Django 5.2.7 on 2025-10-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='genre',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Modern Drama', 'Modern Drama'), ('Historical', 'Historical'), ('Comedy', 'Comedy'), ('Childrens Fiction', "Children's Fiction"), ('Fantasy/Mythology', 'Fantasy/Mythology')], default='Thriller', max_length=30),
        ),
    ]
