# Generated by Django 5.2.7 on 2025-10-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, help_text='Project cover image URL (optional)', max_length=300),
        ),
    ]
