# Generated by Django 5.2.7 on 2025-10-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='poemstart',
        ),
        migrations.RemoveField(
            model_name='project',
            name='storystart',
        ),
        migrations.AddField(
            model_name='project',
            name='starting_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
