# Generated by Django 5.2.7 on 2025-10-30 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_pledge_add_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(help_text='Number of verses/paragraphs contributed', validators=[django.core.validators.MinValueValidator(1, message='Must contribute at least 1 verse/paragraph'), django.core.validators.MaxValueValidator(20, message='Cannot exceed 10 verses/paragraphs per contribution')]),
        ),
    ]
