# Generated by Django 5.2.7 on 2025-12-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_type',
            field=models.CharField(choices=[('story', 'Story'), ('poem', 'Poem')], default='story', max_length=20),
        ),
    ]
