# Generated by Django 5.2.7 on 2025-12-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_pledge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
