# Generated by Django 5.2.7 on 2025-10-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_poemstart_remove_project_storystart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='add_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
